### ISSUE TITLE
Amendment editor toolbar popup

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#12]
Add an extra toolbar icon to the discourse editor allowing users to popup an amendment editor using a template for specific fields: titel, toelichting, beschrijving, etc.

**Comment by kgish** [comment]
![screenshot from 2016-12-22 20-17-08](https://cloud.githubusercontent.com/assets/79195/21437816/56108bfe-c886-11e6-8f3d-9d5c20488ecc.png)
![screenshot from 2016-12-22 19-31-33](https://cloud.githubusercontent.com/assets/79195/21437817/5610e856-c886-11e6-80de-3124ac0ebdf2.png)

**Comment by kgish** [comment]
Added the following to `confif/locales/client.nl.yml`
```
nl:
  js:
    pvda:
      admin:
        ...
      create-motion-template:
        title: 'Nieuwe motie'
        introduction-label: 'Introductie'
        introduction-placeholder: 'WAAROM IS JE MOTIE ACTUEEL, WAT CONSTATEER JE EN OVERWEEG JE?'
        introduction-marker: '## Introductie'
        text-label: 'Tekst'
        text-placeholder: 'AAN WIE RICHT JE DE MOTIE EN WAT MOETEN ZIJ DOEN?'
        text-marker: '## Tekst'
        cancel: 'Annuleren'
        save: 'Opslaan'
```
