### ISSUE TITLE
Site settings hide elements

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-pvda-plugin#24]
Create a more generic site setting for hiding elements on pages.

For example:

```
plugins:
  ...
  pvda_hide_elements:
    default: '/blah:["#banner .close","#hide-me"],'
```

which on the `/blah` path would hide the elements with `#banner .close` and `#hide-me` selectors.
